380.68-alpha1-5e075f7

diff --git a/staging/sbin/fsadm b/staging/sbin/fsadm
--- a/staging/sbin/fsadm
+++ b/staging/sbin/fsadm
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# Copyright (C) 2007-2012 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2007-2017 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -32,7 +32,7 @@
 TOOL=fsadm
 
 _SAVEPATH=$PATH
-PATH=/sbin:/usr/sbin:/bin:/usr/sbin:$PATH
+PATH="/sbin:/usr/sbin:/bin:/usr/sbin:$PATH"
 
 # utilities
 TUNE_EXT=tune2fs
@@ -111,7 +111,7 @@ tool_usage() {
 }
 
 verbose() {
-	test -n "$VERB" && echo "$TOOL: $@" || true
+	test -z "$VERB" || echo "$TOOL:" "$@"
 }
 
 # Support multi-line error messages
@@ -124,10 +124,10 @@ error() {
 
 dry() {
 	if [ "$DRY" -ne 0 ]; then
-		verbose "Dry execution $@"
+		verbose "Dry execution" "$@"
 		return 0
 	fi
-	verbose "Executing $@"
+	verbose "Executing" "$@"
 	"$@"
 }
 
@@ -152,11 +152,11 @@ cleanup() {
 		export _FSADM_YES _FSADM_EXTOFF
 		unset FSADM_RUNNING
 		test -n "$LVM_BINARY" && PATH=$_SAVEPATH
-		dry exec "$LVM" lvresize $VERB $FORCE -r -L${NEWSIZE}b "$VOLUME_ORIG"
+		dry exec "$LVM" lvresize $VERB $FORCE -r -L"${NEWSIZE}b" "$VOLUME_ORIG"
 	fi
 
 	# error exit status for break
-	exit ${1:-1}
+	exit "${1:-1}"
 }
 
 # convert parameter from Exa/Peta/Tera/Giga/Mega/Kilo/Bytes and blocks
@@ -173,9 +173,9 @@ decode_size() {
 	     *) NEWSIZE=$(( $1 * $2 )) ;;
 	esac
 	#NEWBLOCKCOUNT=$(round_block_size $NEWSIZE $2)
-	NEWBLOCKCOUNT=$(( $NEWSIZE / $2 ))
+	NEWBLOCKCOUNT=$(( NEWSIZE / $2 ))
 
-	if [ $DO_LVRESIZE -eq 1 ]; then
+	if [ "$DO_LVRESIZE" -eq 1 ]; then
 		# start lvresize, but first cleanup mounted dirs
 		DO_LVRESIZE=2
 		cleanup 0
@@ -204,13 +204,13 @@ detect_fs() {
 	case "$RVOLUME" in
 	  # hardcoded /dev  since udev does not create these entries elsewhere
 	  /dev/dm-[0-9]*)
-		read </sys/block/${RVOLUME#/dev/}/dm/name SYSVOLUME 2>&1 && VOLUME="$DM_DEV_DIR/mapper/$SYSVOLUME"
-		read </sys/block/${RVOLUME#/dev/}/dev MAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
+		read -r <"/sys/block/${RVOLUME#/dev/}/dm/name" SYSVOLUME 2>&1 && VOLUME="$DM_DEV_DIR/mapper/$SYSVOLUME"
+		read -r <"/sys/block/${RVOLUME#/dev/}/dev" MAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
 		MAJOR=${MAJORMINOR%%:*}
 		MINOR=${MAJORMINOR##*:}
 		;;
 	  *)
-		STAT=$(stat --format "MAJOR=\$((0x%t)) MINOR=\$((0x%T))" ${RVOLUME})
+		STAT=$(stat --format "MAJOR=\$((0x%t)) MINOR=\$((0x%T))" "$RVOLUME")
 		test -n "$STAT" || error "Cannot get major:minor for \"$VOLUME\"."
 		eval "$STAT"
 		MAJORMINOR="${MAJOR}:${MINOR}"
@@ -229,8 +229,10 @@ detect_fs() {
 # Check that passed mounted MAJOR:MINOR is not matching $MAJOR:MINOR of resized $VOLUME
 validate_mounted_major_minor() {
 	test "$1" = "$MAJORMINOR" || {
-		local REFNAME=$(dmsetup info -c -j "${1%%:*}" -m "${1##*:}" -o name --noheadings 2>/dev/null)
-		local CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings 2>/dev/null)
+		local REFNAME
+		local CURNAME
+		REFNAME=$(dmsetup info -c -j "${1%%:*}" -m "${1##*:}" -o name --noheadings 2>/dev/null)
+		CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings 2>/dev/null)
 		error "Cannot ${CHECK+CHECK}${RESIZE+RESIZE} device \"$VOLUME\" without umounting filesystem $MOUNTED first." \
 		      "Mounted filesystem is using device $CURNAME, but referenced device is $REFNAME." \
 		      "Filesystem utilities currently do not support renamed devices."
@@ -243,10 +245,12 @@ validate_mounted_major_minor() {
 # abort further command processing
 check_valid_mounted_device() {
 	local MOUNTEDMAJORMINOR
-	local VOL=$("$READLINK" $READLINK_E "$1")
-	local CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings)
+	local VOL
+	local CURNAME
 	local SUGGEST="Possibly device \"$1\" has been renamed to \"$CURNAME\"?"
 
+	VOL=$("$READLINK" $READLINK_E "$1")
+	CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings)
 	# more confused, device is not DM....
 	test -n "$CURNAME" || SUGGEST="Mounted volume is not a device mapper device???"
 
@@ -258,7 +262,7 @@ check_valid_mounted_device() {
 	case "$VOL" in
 	  # hardcoded /dev  since udev does not create these entries elsewhere
 	  /dev/dm-[0-9]*)
-		read </sys/block/${VOL#/dev/}/dev MOUNTEDMAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
+		read -r <"/sys/block/${VOL#/dev/}/dev" MOUNTEDMAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
 		;;
 	  *)
 		STAT=$(stat --format "MOUNTEDMAJORMINOR=\$((0x%t)):\$((0x%T))" "$VOL")
@@ -280,20 +284,20 @@ detect_mounted_with_proc_self_mountinfo() {
 	# Use 'find' to not fail on to long list of args with too many pids
 	# only 1st. line is needed
 	test -z "$MOUNTED" &&
-		test $(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR") -gt 0 &&
+		test "$(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR")" -gt 0 &&
 		MOUNTED=$(find "$PROCDIR" -maxdepth 2 -name mountinfo -print0 |  xargs -0 "$GREP" "^[0-9]* [0-9]* $MAJORMINOR " 2>/dev/null | head -1 2>/dev/null)
 
 	# TODO: for performance compare with sed and stop with 1st. match:
 	# sed -n "/$MAJORMINOR/ {;p;q;}"
 
 	# extract 2nd field after ' - ' separator as mouted device
-	MOUNTDEV=$(echo ${MOUNTED##* - } | cut -d ' ' -f 2)
-	MOUNTDEV=$(echo -n -e ${MOUNTDEV})
+	MOUNTDEV=$(echo "${MOUNTED##* - }" | cut -d ' ' -f 2)
+	MOUNTDEV=$(echo -n -e "$MOUNTDEV")
 
 	# extract 5th field as mount point
 	# echo -e translates \040 to spaces
-	MOUNTED=$(echo ${MOUNTED} | cut -d ' ' -f 5)
-	MOUNTED=$(echo -n -e ${MOUNTED})
+	MOUNTED=$(echo "$MOUNTED" | cut -d ' ' -f 5)
+	MOUNTED=$(echo -n -e "$MOUNTED")
 
 	test -n "$MOUNTED" || return 1   # Not seen mounted anywhere
 
@@ -310,11 +314,11 @@ detect_mounted_with_proc_mounts() {
 	# for empty string try again with real volume name
 	test -z "$MOUNTED" && MOUNTED=$("$GREP" "^$RVOLUME[ \t]" "$PROCMOUNTS")
 
-	MOUNTDEV=$(echo -n -e ${MOUNTED%% *})
+	MOUNTDEV=$(echo -n -e "${MOUNTED%% *}")
 	# cut device name prefix and trim everything past mountpoint
 	# echo translates \040 to spaces
 	MOUNTED=${MOUNTED#* }
-	MOUNTED=$(echo -n -e ${MOUNTED%% *})
+	MOUNTED=$(echo -n -e "${MOUNTED%% *}")
 
 	# for systems with different device names - check also mount output
 	if test -z "$MOUNTED" ; then
@@ -333,13 +337,13 @@ detect_mounted_with_proc_mounts() {
 
 	# If still nothing found and volume is in use
 	# check every known mount point against MAJOR:MINOR
-	if test $(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR") -gt 0 ; then
+	if test "$(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR")" -gt 0 ; then
 		while IFS=$'\n' read -r i ; do
-			MOUNTDEV=$(echo -n -e ${i%% *})
+			MOUNTDEV=$(echo -n -e "${i%% *}")
 			MOUNTED=${i#* }
-			MOUNTED=$(echo -n -e ${MOUNTED%% *})
-			STAT=$(stat --format "%d" $MOUNTED)
-			validate_mounted_major_minor $(decode_major_minor "$STAT")
+			MOUNTED=$(echo -n -e "${MOUNTED%% *}")
+			STAT=$(stat --format "%d" "$MOUNTED")
+			validate_mounted_major_minor "$(decode_major_minor "$STAT")"
 		done < "$PROCMOUNTS"
 	fi
 
@@ -370,7 +374,7 @@ detect_device_size() {
 		test -n "$DEVSIZE" || error "Cannot read size of device \"$VOLUME\"."
 		SSSIZE=$("$BLOCKDEV" --getss "$VOLUME")
 		test -n "$SSSIZE" || error "Cannot read sector size of device \"$VOLUME\"."
-		DEVSIZE=$(($DEVSIZE * $SSSIZE))
+		DEVSIZE=$(("$DEVSIZE" * "$SSSIZE"))
 	fi
 }
 
@@ -393,7 +397,7 @@ temp_umount() {
 }
 
 yes_no() {
-	echo -n "$@? [Y|n] "
+	echo -n "$@" "? [Y|n] "
 
 	if [ -n "$YES" ]; then
 		echo y ; return 0
@@ -419,7 +423,9 @@ try_umount() {
 }
 
 validate_parsing() {
-	test -n "$BLOCKSIZE" && test -n "$BLOCKCOUNT" || error "Cannot parse $1 output."
+	if test -z "$BLOCKSIZE" || test -z "$BLOCKCOUNT" ; then
+		error "Cannot parse $1 output."
+	fi
 }
 ####################################
 # Resize ext2/ext3/ext4 filesystem
@@ -438,11 +444,11 @@ resize_ext() {
 		esac
 	done
 	validate_parsing "$TUNE_EXT"
-	decode_size $1 $BLOCKSIZE
+	decode_size "$1" "$BLOCKSIZE"
 	FSFORCE=$FORCE
 
-	if [ "$NEWBLOCKCOUNT" -lt "$BLOCKCOUNT" -o "$EXTOFF" -eq 1 ]; then
-		test $IS_MOUNTED -eq 1 && verbose "$RESIZE_EXT needs unmounted filesystem" && try_umount
+	if test "$NEWBLOCKCOUNT" -lt "$BLOCKCOUNT" || test "$EXTOFF" -eq 1 ; then
+		test "$IS_MOUNTED" -eq 1 && verbose "$RESIZE_EXT needs unmounted filesystem" && try_umount
 		REMOUNT=$MOUNTED
 		if test -n "$MOUNTED" ; then
 			# Forced fsck -f for umounted extX filesystem.
@@ -454,7 +460,7 @@ resize_ext() {
 	fi
 
 	verbose "Resizing filesystem on device \"$VOLUME\" to $NEWSIZE bytes ($BLOCKCOUNT -> $NEWBLOCKCOUNT blocks of $BLOCKSIZE bytes)"
-	dry "$RESIZE_EXT" $FSFORCE "$VOLUME" $NEWBLOCKCOUNT
+	dry "$RESIZE_EXT" $FSFORCE "$VOLUME" "$NEWBLOCKCOUNT"
 }
 
 #############################
@@ -473,12 +479,12 @@ resize_reiser() {
 		esac
 	done
 	validate_parsing "$TUNE_REISER"
-	decode_size $1 $BLOCKSIZE
+	decode_size "$1" "$BLOCKSIZE"
 	verbose "Resizing \"$VOLUME\" $BLOCKCOUNT -> $NEWBLOCKCOUNT blocks ($NEWSIZE bytes, bs: $NEWBLOCKCOUNT)"
 	if [ -n "$YES" ]; then
-		echo y | dry "$RESIZE_REISER" -s $NEWSIZE "$VOLUME"
+		echo y | dry "$RESIZE_REISER" -s "$NEWSIZE" "$VOLUME"
 	else
-		dry "$RESIZE_REISER" -s $NEWSIZE "$VOLUME"
+		dry "$RESIZE_REISER" -s "$NEWSIZE" "$VOLUME"
 	fi
 }
 
@@ -503,11 +509,11 @@ resize_xfs() {
 	BLOCKSIZE=${BLOCKSIZE%%[^0-9]*}
 	BLOCKCOUNT=${BLOCKCOUNT%%[^0-9]*}
 	validate_parsing "$TUNE_XFS"
-	decode_size $1 $BLOCKSIZE
-	if [ $NEWBLOCKCOUNT -gt $BLOCKCOUNT ]; then
+	decode_size "$1" "$BLOCKSIZE"
+	if [ "$NEWBLOCKCOUNT" -gt "$BLOCKCOUNT" ]; then
 		verbose "Resizing Xfs mounted on \"$MOUNTPOINT\" to fill device \"$VOLUME\""
-		dry "$RESIZE_XFS" $MOUNTPOINT
-	elif [ $NEWBLOCKCOUNT -eq $BLOCKCOUNT ]; then
+		dry "$RESIZE_XFS" "$MOUNTPOINT"
+	elif [ "$NEWBLOCKCOUNT" -eq "$BLOCKCOUNT" ]; then
 		verbose "Xfs filesystem already has the right size"
 	else
 		error "Xfs filesystem shrinking is unsupported."
@@ -567,7 +573,7 @@ check() {
 		case "$LASTMOUNT" in
 		  *"n/a") ;; # nothing to do - system was not mounted yet
 		  *)
-			LASTDIFF=$(diff_dates $LASTMOUNT $LASTCHECKED)
+			LASTDIFF=$(diff_dates "$LASTMOUNT" "$LASTCHECKED")
 			if test "$LASTDIFF" -gt 0 ; then
 				verbose "Filesystem has not been checked after the last mount, using fsck -f"
 				FORCE="-f"
@@ -613,11 +619,11 @@ for i in "$TUNE_EXT" "$RESIZE_EXT" "$TUNE_REISER" "$RESIZE_REISER" \
 done
 
 "$LVM" version >"$NULL" 2>&1 || error "Could not run lvm binary \"$LVM\"."
-$("$READLINK" -e / >"$NULL" 2>&1) || READLINK_E="-f"
+"$READLINK" -e / >"$NULL" 2>&1 || READLINK_E="-f"
 TEST64BIT=$(( 1000 * 1000000000000 ))
 test "$TEST64BIT" -eq 1000000000000000 || error "Shell does not handle 64bit arithmetic."
-$(echo Y | "$GREP" Y >"$NULL") || error "Grep does not work properly."
-test $("$DATE" -u -d"Jan 01 00:00:01 1970" +%s) -eq 1 || error "Date translation does not work."
+echo Y | "$GREP" Y >"$NULL" || error "Grep does not work properly."
+test "$("$DATE" -u -d"Jan 01 00:00:01 1970" +%s)" -eq 1 || error "Date translation does not work."
 
 
 if [ "$#" -eq 0 ] ; then
@@ -635,14 +641,14 @@ do
 	  "-e"|"--ext-offline") EXTOFF=1 ;;
 	  "-y"|"--yes") YES="-y" ;;
 	  "-l"|"--lvresize") DO_LVRESIZE=1 ;;
-	  "check") CHECK="$2" ; shift ;;
-	  "resize") RESIZE="$2"; NEWSIZE="$3" ; shift 2 ;;
+	  "check") CHECK=$2 ; shift ;;
+	  "resize") RESIZE=$2 ; NEWSIZE=$3 ; shift 2 ;;
 	  *) error "Wrong argument \"$1\". (see: $TOOL --help)"
 	esac
 	shift
 done
 
-test "$YES" = "-y" || YES=
+test "$YES" = "-y" || YES=""
 test "$EXTOFF" -eq 1 || EXTOFF=0
 
 if [ -n "$CHECK" ]; then
diff --git a/staging/sbin/lvmdump b/staging/sbin/lvmdump
--- a/staging/sbin/lvmdump
+++ b/staging/sbin/lvmdump
@@ -1,7 +1,7 @@
 #!/bin/bash
 # We use some bash-isms (getopts?)
 
-# Copyright (C) 2007-2015 Red Hat, Inc. All rights reserved.
+# Copyright (C) 2007-2017 Red Hat, Inc. All rights reserved.
 #
 # This file is part of LVM2.
 #
@@ -53,7 +53,7 @@ LVMPOLLD_SOCKET=${LVM_LVMPOLLD_SOCKET-/var/run/lvm/lvmpolld.socket}
 die() {
     code=$1; shift
     echo "$@" 1>&2
-    exit $code
+    exit "$code"
 }
 
 "$LVM" version >& /dev/null || die 2 "Could not run lvm binary '$LVM'"
@@ -98,20 +98,20 @@ while getopts :acd:hlpmus opt; do
 	esac
 done
 
-NOW=`$DATE -u +%G%m%d%k%M%S | $TR -d ' '`
+NOW=$("$DATE" -u +%G%m%d%k%M%S | "$TR" -d ' ')
 if test -n "$userdir"; then
-	dir="$userdir"
+	dir=$userdir
 else
 	dirbase="lvmdump-$HOSTNAME-$NOW"
 	dir="$HOME/$dirbase"
 fi
 
-if test -d $dir ; then
-	(shopt -s nullglob dotglob; test -r $dir -a -w $dir -a -x $dir && cd $dir && files=(*) && ((! ${#files[@]}))) || \
+if test -d "$dir" ; then
+	(shopt -s nullglob dotglob; test -r "$dir" -a -w "$dir" -a -x "$dir" && cd "$dir" && files=(*) && ((! ${#files[@]}))) || \
 		die 5 "Fatal: directory $dir already exists and is not empty or inaccessible"
 else
-	test -e $dir && die 3 "Fatal: $dir already exists"
-	$MKDIR -p $dir || die 4 "Fatal: could not create $dir"
+	test -e "$dir" && die 3 "Fatal: $dir already exists"
+	"$MKDIR" -p "$dir" || die 4 "Fatal: could not create $dir"
 fi
 
 log="$dir/lvmdump.log"
@@ -127,7 +127,7 @@ log() {
 }
 
 warnings() {
-	if test "$UID" != "0" && test "$EUID" != "0"; then
+	if test "$UID" != 0 && test "$EUID" != 0; then
 		myecho "WARNING! Running as non-privileged user, dump is likely incomplete!"
 	elif test "$DMSETUP" = ":"; then
 		myecho "WARNING! Could not run dmsetup, dump is likely incomplete."
@@ -139,7 +139,7 @@ warnings
 myecho "Creating dump directory: $dir"
 echo " "
 
-if (( $advanced )); then
+if (( advanced )); then
 	myecho "Gathering LVM volume info..."
 
 	myecho "  vgscan..."
@@ -158,13 +158,14 @@ if (( $advanced )); then
 	log "\"$LVM\" vgs -v >> \"$dir/vgs\" 2>> \"$log\""
 fi
 
-if (( $clustered )); then
+if (( clustered )); then
 	myecho "Gathering cluster info..."
 
 	{
 	for i in nodes status services; do
-		cap_i=$(echo $i|tr a-z A-Z)
-		printf "$cap_i:\n----------------------------------\n"
+		cap_i=$(echo "$i"|tr a-z A-Z)
+		echo "$cap_i:"
+		echo "----------------------------------"
 		log "cman_tool $i 2>> \"$log\""
 		echo
 	done
@@ -193,18 +194,20 @@ if (( $clustered )); then
 		echo "MASTER:"
 		cat /debug/dlm/clvmd_master
 	fi
-	} >> $dir/cluster_info
+	} >> "$dir/cluster_info"
 fi
 
 myecho "Gathering LVM & device-mapper version info..."
-echo "LVM VERSION:" >> "$dir/versions"
-"$LVM" lvs --version >> "$dir/versions" 2>> "$log"
-echo "DEVICE MAPPER VERSION:" >> "$dir/versions"
-"$DMSETUP" --version >> "$dir/versions" 2>> "$log"
-echo "KERNEL VERSION:" >> "$dir/versions"
-"$UNAME" -a >> "$dir/versions" 2>> "$log"
-echo "DM TARGETS VERSIONS:" >> "$dir/versions"
-"$DMSETUP" targets >> "$dir/versions" 2>> "$log"
+{
+	echo "LVM VERSION:"
+	"$LVM" lvs --version
+	echo "DEVICE MAPPER VERSION:"
+	"$DMSETUP" --version
+	echo "KERNEL VERSION:"
+	"$UNAME" -a
+	echo "DM TARGETS VERSIONS:"
+	"$DMSETUP" targets
+} >> "$dir/versions" 2>> "$log"
 
 myecho "Gathering dmsetup info..."
 log "\"$DMSETUP\" info -c >> \"$dir/dmsetup_info\" 2>> \"$log\""
@@ -233,45 +236,45 @@ myecho "Gathering /sys/block listing..."
 log "$LS -laR /sys/block >> \"$dir/sysblock_listing\"  2>> \"$log\""
 log "$LS -laR /sys/devices/virtual/block >> \"$dir/sysblock_listing\"  2>> \"$log\""
 
-if (( $metadata )); then
+if (( metadata )); then
 	myecho "Gathering LVM metadata from Physical Volumes..."
 
 	log "$MKDIR -p \"$dir/metadata\""
 
-	pvs="$("$LVM" pvs --separator , --noheadings --units s --nosuffix -o \
-	    name,pe_start 2>> "$log" | $SED -e 's/^ *//')"
+	pvs=$("$LVM" pvs --separator , --noheadings --units s --nosuffix -o \
+	    name,pe_start 2>> "$log" | $SED -e 's/^ *//')
 	for line in $pvs
 	do
 		test -z "$line" && continue
-		pv="$(echo $line | $CUT -d, -f1)"
-		pe_start="$(echo $line | $CUT -d, -f2)"
-		name="$($BASENAME "$pv")"
+		pv=$(echo "$line" | "$CUT" -d, -f1)
+		pe_start=$(echo "$line" | "$CUT" -d, -f2)
+		name=$("$BASENAME" "$pv")
 		myecho "  $pv"
 		log "$DD if=$pv \"of=$dir/metadata/$name\" $DDFLAGS bs=512 count=$pe_start 2>> \"$log\""
 	done
 fi
 
-if (( $sysreport )); then
+if (( sysreport )); then
 	myecho "Gathering system info..."
 
 	sysreport_dir="$dir/sysreport"
 	log_lines=10000
 
-	SYSTEMCTL=$(which systemctl 2>> $log)
-	JOURNALCTL=$(which journalctl 2>> $log)
-	LSBLK=$(which lsblk 2>> $log)
+	SYSTEMCTL=$(which systemctl 2>> "$log")
+	JOURNALCTL=$(which journalctl 2>> "$log")
+	LSBLK=$(which lsblk 2>> "$log")
 
 	log "$MKDIR -p \"$sysreport_dir\""
 
 	if test -z "LSBLK"; then
 		myecho "WARNING: lsblk not found"
 	else
-		if $LSBLK --help | $GREP -- --output-all >/dev/null; then
+		if "$LSBLK" --help | "$GREP" -- --output-all >/dev/null; then
 			log "$LSBLK -O >> \"$sysreport_dir/lsblk_O\""
 		else
 			log "$LSBLK >> \"$sysreport_dir/lsblk\""
 		fi
-		if $LSBLK --help | $GREP -- --inverse >/dev/null; then
+		if "$LSBLK" --help | "$GREP" -- --inverse >/dev/null; then
 			log "$LSBLK -s >> \"$sysreport_dir/lsblk_s\""
 		fi
 	fi
@@ -294,13 +297,13 @@ if (( $sysreport )); then
 						   lvm2-activation-net.service \
 						   > \"$sysreport_dir/systemd_lvm2_services_status\" 2>> \"$log\""
 		log "$SYSTEMCTL list-units -l -a --no-legend --no-pager > \"$sysreport_dir/systemd_unit_list\" 2>> \"$log\""
-		for unit in $(cat $sysreport_dir/systemd_unit_list | $GREP lvm2-pvscan | cut -d " " -f 1); do
+		for unit in $("$GREP" lvm2-pvscan "$sysreport_dir/systemd_unit_list" | cut -d " " -f 1); do
 			log "$SYSTEMCTL status -l --no-pager -n $log_lines -o short-precise $unit >> \"$sysreport_dir/systemd_lvm2_pvscan_service_status\""
 		done
 	fi
 fi
 
-if (( $udev )); then
+if (( udev )); then
 	myecho "Gathering udev info..."
 
 	udev_dir="$dir/udev"
@@ -314,14 +317,14 @@ if (( $udev )); then
 	log "$CP -RL --preserve=all /lib/udev/rules.d \"$udev_dir/rules_lib\" 2>> \"$log\""
 fi
 
-if (( $lvmetad )); then
+if (( lvmetad )); then
     (echo 'request="dump"'; echo '##') | {
-	if type -p $SOCAT >& /dev/null; then
+	if type -p "$SOCAT" >& /dev/null; then
 	    echo "$SOCAT unix-connect:$LVMETAD_SOCKET -" >> "$log"
-	    $SOCAT "unix-connect:$LVMETAD_SOCKET" - 2>> "$log"
-	elif echo | $NC -U "$LVMETAD_SOCKET"; then
+	    "$SOCAT" "unix-connect:$LVMETAD_SOCKET" - 2>> "$log"
+	elif echo | "$NC" -U "$LVMETAD_SOCKET"; then
 	    echo "$NC -U $LVMETAD_SOCKET" >> "$log"
-	    $NC -U "$LVMETAD_SOCKET" 2>> "$log"
+	    "$NC" -U "$LVMETAD_SOCKET" 2>> "$log"
 	else
 	    myecho "WARNING: Neither socat nor nc -U seems to be available." 1>&2
 	    echo "# DUMP FAILED"
@@ -330,14 +333,14 @@ if (( $lvmetad )); then
     } > "$dir/lvmetad.txt"
 fi
 
-if (( $lvmpolld )); then
+if (( lvmpolld )); then
     (echo 'request="dump"'; echo '##') | {
-	if type -p $SOCAT >& /dev/null; then
+	if type -p "$SOCAT" >& /dev/null; then
 	    echo "$SOCAT unix-connect:$LVMPOLLD_SOCKET -" >> "$log"
-	    $SOCAT "unix-connect:$LVMPOLLD_SOCKET" - 2>> "$log"
-	elif echo | $NC -U "$LVMPOLLD_SOCKET"; then
+	    "$SOCAT" "unix-connect:$LVMPOLLD_SOCKET" - 2>> "$log"
+	elif echo | "$NC" -U "$LVMPOLLD_SOCKET"; then
 	    echo "$NC -U $LVMPOLLD_SOCKET" >> "$log"
-	    $NC -U "$LVMPOLLD_SOCKET" 2>> "$log"
+	    "$NC" -U "$LVMPOLLD_SOCKET" 2>> "$log"
 	else
 	    myecho "WARNING: Neither socat nor nc -U seems to be available." 1>&2
 	    echo "# DUMP FAILED"
