updated bins

diff --git a/staging/sbin/fsadm b/staging/sbin/fsadm
--- a/staging/sbin/fsadm
+++ b/staging/sbin/fsadm
@@ -75,8 +75,9 @@ BLOCKCOUNT=
 MOUNTPOINT=
 MOUNTED=
 REMOUNT=
-PROCMOUNTS="/proc/mounts"
-PROCSELFMOUNTINFO="/proc/self/mountinfo"
+PROCDIR="/proc"
+PROCMOUNTS="$PROCDIR/mounts"
+PROCSELFMOUNTINFO="$PROCDIR/self/mountinfo"
 NULL="$DM_DEV_DIR/null"
 
 IFS_OLD=$IFS
@@ -113,8 +114,11 @@ verbose() {
 	test -n "$VERB" && echo "$TOOL: $@" || true
 }
 
+# Support multi-line error messages
 error() {
-	echo "$TOOL: $@" >&2
+	for i in "$@" ;  do
+		echo "$TOOL: $i" >&2
+	done
 	cleanup 1
 }
 
@@ -178,52 +182,135 @@ decode_size() {
 	fi
 }
 
+decode_major_minor() {
+	# 0x00000fff00  mask MAJOR
+	# 0xfffff000ff  mask MINOR
+
+	#MINOR=$(( $1 / 1048576 ))
+	#MAJOR=$(( ($1 - ${MINOR} * 1048576) / 256 ))
+	#MINOR=$(( $1 - ${MINOR} * 1048576 - ${MAJOR} * 256 + ${MINOR} * 256))
+
+	echo "$(( ( $1 >> 8 ) & 4095 )):$(( ( ( $1 >> 12 ) & 268435200 ) | ( $1 & 255 ) ))"
+}
+
 # detect filesystem on the given device
 # dereference device name if it is symbolic link
 detect_fs() {
 	VOLUME_ORIG=$1
 	VOLUME=${1/#"${DM_DEV_DIR}/"/}
-	VOLUME=$("$READLINK" $READLINK_E "$DM_DEV_DIR/$VOLUME") || error "Cannot get readlink \"$1\""
+	VOLUME=$("$READLINK" $READLINK_E "$DM_DEV_DIR/$VOLUME")
+	test -n "$VOLUME" || error "Cannot get readlink \"$1\"."
 	RVOLUME=$VOLUME
 	case "$RVOLUME" in
-          # hardcoded /dev  since udev does not create these entries elsewhere
+	  # hardcoded /dev  since udev does not create these entries elsewhere
 	  /dev/dm-[0-9]*)
 		read </sys/block/${RVOLUME#/dev/}/dm/name SYSVOLUME 2>&1 && VOLUME="$DM_DEV_DIR/mapper/$SYSVOLUME"
-		read </sys/block/${RVOLUME#/dev/}/dev MAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\""
+		read </sys/block/${RVOLUME#/dev/}/dev MAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
+		MAJOR=${MAJORMINOR%%:*}
+		MINOR=${MAJORMINOR##*:}
 		;;
 	  *)
-		STAT=$(stat --format "MAJOR=%t MINOR=%T" ${RVOLUME}) || error "Cannot get major:minor for \"$VOLUME\""
-		eval $STAT
-		MAJOR=$((0x${MAJOR}))
-		MINOR=$((0x${MINOR}))
-		MAJORMINOR=${MAJOR}:${MINOR}
+		STAT=$(stat --format "MAJOR=\$((0x%t)) MINOR=\$((0x%T))" ${RVOLUME})
+		test -n "$STAT" || error "Cannot get major:minor for \"$VOLUME\"."
+		eval "$STAT"
+		MAJORMINOR="${MAJOR}:${MINOR}"
 		;;
 	esac
 	# use null device as cache file to be sure about the result
 	# not using option '-o value' to be compatible with older version of blkid
-	FSTYPE=$("$BLKID" -c "$NULL" -s TYPE "$VOLUME") || error "Cannot get FSTYPE of \"$VOLUME\""
+	FSTYPE=$("$BLKID" -c "$NULL" -s TYPE "$VOLUME")
+	test -n "$FSTYPE" || error "Cannot get FSTYPE of \"$VOLUME\"."
 	FSTYPE=${FSTYPE##*TYPE=\"} # cut quotation marks
 	FSTYPE=${FSTYPE%%\"*}
-	verbose "\"$FSTYPE\" filesystem found on \"$VOLUME\""
+	verbose "\"$FSTYPE\" filesystem found on \"$VOLUME\"."
 }
 
-detect_mounted_with_proc_self_mountinfo()  {
-	MOUNTED=$("$GREP" "^[0-9]* [0-9]* $MAJORMINOR " "$PROCSELFMOUNTINFO")
 
-	# extract 5th field which is mount point
+# Check that passed mounted MAJOR:MINOR is not matching $MAJOR:MINOR of resized $VOLUME
+validate_mounted_major_minor() {
+	test "$1" = "$MAJORMINOR" || {
+		local REFNAME=$(dmsetup info -c -j "${1%%:*}" -m "${1##*:}" -o name --noheadings 2>/dev/null)
+		local CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings 2>/dev/null)
+		error "Cannot ${CHECK+CHECK}${RESIZE+RESIZE} device \"$VOLUME\" without umounting filesystem $MOUNTED first." \
+		      "Mounted filesystem is using device $CURNAME, but referenced device is $REFNAME." \
+		      "Filesystem utilities currently do not support renamed devices."
+	}
+}
+
+# ATM fsresize & fsck tools are not able to work properly
+# when mounted device has changed its name.
+# So whenever such device no longer exists with original name
+# abort further command processing
+check_valid_mounted_device() {
+	local MOUNTEDMAJORMINOR
+	local VOL=$("$READLINK" $READLINK_E "$1")
+	local CURNAME=$(dmsetup info -c -j "$MAJOR" -m "$MINOR" -o name --noheadings)
+	local SUGGEST="Possibly device \"$1\" has been renamed to \"$CURNAME\"?"
+
+	# more confused, device is not DM....
+	test -n "$CURNAME" || SUGGEST="Mounted volume is not a device mapper device???"
+
+	test -n "$VOL" ||
+		error "Cannot access device \"$1\" referenced by mounted filesystem \"$MOUNTED\"." \
+		"$SUGGEST" \
+		"Filesystem utilities currently do not support renamed devices."
+
+	case "$VOL" in
+	  # hardcoded /dev  since udev does not create these entries elsewhere
+	  /dev/dm-[0-9]*)
+		read </sys/block/${VOL#/dev/}/dev MOUNTEDMAJORMINOR 2>&1 || error "Cannot get major:minor for \"$VOLUME\"."
+		;;
+	  *)
+		STAT=$(stat --format "MOUNTEDMAJORMINOR=\$((0x%t)):\$((0x%T))" "$VOL")
+		test -n "$STAT" || error "Cannot get major:minor for \"$VOLUME\"."
+		eval "$STAT"
+		;;
+	esac
+
+	validate_mounted_major_minor "$MOUNTEDMAJORMINOR"
+}
+
+detect_mounted_with_proc_self_mountinfo() {
+	# Check self mountinfo
+	# grab major:minor mounted_device mount_point
+	MOUNTED=$("$GREP" "^[0-9]* [0-9]* $MAJORMINOR " "$PROCSELFMOUNTINFO" 2>/dev/null | head -1)
+
+	# If device is opened and not yet found as self mounted
+	# check all other mountinfos (since it can be mounted in cgroups)
+	# Use 'find' to not fail on to long list of args with too many pids
+	# only 1st. line is needed
+	test -z "$MOUNTED" &&
+		test $(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR") -gt 0 &&
+		MOUNTED=$(find "$PROCDIR" -maxdepth 2 -name mountinfo -print0 |  xargs -0 "$GREP" "^[0-9]* [0-9]* $MAJORMINOR " 2>/dev/null | head -1 2>/dev/null)
+
+	# TODO: for performance compare with sed and stop with 1st. match:
+	# sed -n "/$MAJORMINOR/ {;p;q;}"
+
+	# extract 2nd field after ' - ' separator as mouted device
+	MOUNTDEV=$(echo ${MOUNTED##* - } | cut -d ' ' -f 2)
+	MOUNTDEV=$(echo -n -e ${MOUNTDEV})
+
+	# extract 5th field as mount point
 	# echo -e translates \040 to spaces
-	MOUNTED=$(echo ${MOUNTED} | cut -d " " -f 5)
+	MOUNTED=$(echo ${MOUNTED} | cut -d ' ' -f 5)
 	MOUNTED=$(echo -n -e ${MOUNTED})
 
-	test -n "$MOUNTED"
+	test -n "$MOUNTED" || return 1   # Not seen mounted anywhere
+
+	check_valid_mounted_device "$MOUNTDEV"
 }
 
-detect_mounted_with_proc_mounts()  {
+# With older systems without /proc/*/mountinfo we may need to check
+# every mount point as cannot easily depend on the name of mounted
+# device (which could have been renamed).
+# We need to visit every mount point and check it's major minor
+detect_mounted_with_proc_mounts() {
 	MOUNTED=$("$GREP" "^$VOLUME[ \t]" "$PROCMOUNTS")
 
 	# for empty string try again with real volume name
 	test -z "$MOUNTED" && MOUNTED=$("$GREP" "^$RVOLUME[ \t]" "$PROCMOUNTS")
 
+	MOUNTDEV=$(echo -n -e ${MOUNTED%% *})
 	# cut device name prefix and trim everything past mountpoint
 	# echo translates \040 to spaces
 	MOUNTED=${MOUNTED#* }
@@ -231,24 +318,43 @@ detect_mounted_with_proc_mounts()  {
 
 	# for systems with different device names - check also mount output
 	if test -z "$MOUNTED" ; then
+		# will not work with spaces in paths
 		MOUNTED=$(LC_ALL=C "$MOUNT" | "$GREP" "^$VOLUME[ \t]")
 		test -z "$MOUNTED" && MOUNTED=$(LC_ALL=C "$MOUNT" | "$GREP" "^$RVOLUME[ \t]")
+		MOUNTDEV=${MOUNTED%% on *}
 		MOUNTED=${MOUNTED##* on }
 		MOUNTED=${MOUNTED% type *} # allow type in the mount name
 	fi
 
-	test -n "$MOUNTED"
+	if test -n "$MOUNTED" ; then
+		check_valid_mounted_device "$MOUNTDEV"
+		return 0  # mounted
+	fi
+
+	# If still nothing found and volume is in use
+	# check every known mount point against MAJOR:MINOR
+	if test $(dmsetup info -c --noheading -o open -j "$MAJOR" -m "$MINOR") -gt 0 ; then
+		while IFS=$'\n' read -r i ; do
+			MOUNTDEV=$(echo -n -e ${i%% *})
+			MOUNTED=${i#* }
+			MOUNTED=$(echo -n -e ${MOUNTED%% *})
+			STAT=$(stat --format "%d" $MOUNTED)
+			validate_mounted_major_minor $(decode_major_minor "$STAT")
+		done < "$PROCMOUNTS"
+	fi
+
+	return 1  # nothing is mounted
 }
 
 # check if the given device is already mounted and where
 # FIXME: resolve swap usage and device stacking
-detect_mounted()  {
+detect_mounted() {
 	if test -e "$PROCSELFMOUNTINFO"; then
 		detect_mounted_with_proc_self_mountinfo
 	elif test -e "$PROCMOUNTS"; then
 		detect_mounted_with_proc_mounts
 	else
-		error "Cannot detect mounted device \"$VOLUME\""
+		error "Cannot detect mounted device \"$VOLUME\"."
 	fi
 }
 
@@ -257,10 +363,13 @@ detect_device_size() {
 	# check if blockdev supports getsize64
 	"$BLOCKDEV" 2>&1 | "$GREP" getsize64 >"$NULL"
 	if test $? -eq 0; then
-		DEVSIZE=$("$BLOCKDEV" --getsize64 "$VOLUME") || error "Cannot read size of device \"$VOLUME\""
+		DEVSIZE=$("$BLOCKDEV" --getsize64 "$VOLUME")
+		test -n "$DEVSIZE" || error "Cannot read size of device \"$VOLUME\"."
 	else
-		DEVSIZE=$("$BLOCKDEV" --getsize "$VOLUME") || error "Cannot read size of device \"$VOLUME\""
-		SSSIZE=$("$BLOCKDEV" --getss "$VOLUME") || error "Cannot block size read device \"$VOLUME\""
+		DEVSIZE=$("$BLOCKDEV" --getsize "$VOLUME")
+		test -n "$DEVSIZE" || error "Cannot read size of device \"$VOLUME\"."
+		SSSIZE=$("$BLOCKDEV" --getss "$VOLUME")
+		test -n "$SSSIZE" || error "Cannot read sector size of device \"$VOLUME\"."
 		DEVSIZE=$(($DEVSIZE * $SSSIZE))
 	fi
 }
@@ -273,14 +382,14 @@ round_up_block_size() {
 }
 
 temp_mount() {
-	dry "$MKDIR" -p -m 0000 "$TEMPDIR" || error "Failed to create $TEMPDIR"
-	dry "$MOUNT" "$VOLUME" "$TEMPDIR" || error "Failed to mount $TEMPDIR"
+	dry "$MKDIR" -p -m 0000 "$TEMPDIR" || error "Failed to create $TEMPDIR."
+	dry "$MOUNT" "$VOLUME" "$TEMPDIR" || error "Failed to mount $TEMPDIR."
 }
 
 temp_umount() {
-	dry "$UMOUNT" "$TEMPDIR" || error "Failed to umount \"$TEMPDIR\""
-	dry "$RMDIR" "${TEMPDIR}" || error "Failed to remove \"$TEMPDIR\""
-	dry "$RMDIR" "${TEMPDIR%%m}" || error "Failed to remove \"${TEMPDIR%%m}\""
+	dry "$UMOUNT" "$TEMPDIR" || error "Failed to umount \"$TEMPDIR\"."
+	dry "$RMDIR" "${TEMPDIR}" || error "Failed to remove \"$TEMPDIR\","
+	dry "$RMDIR" "${TEMPDIR%%m}" || error "Failed to remove \"${TEMPDIR%%m}\"."
 }
 
 yes_no() {
@@ -292,19 +401,25 @@ yes_no() {
 
 	while read -r -s -n 1 ANS ; do
 		case "$ANS" in
-		 "y" | "Y" | "") echo y ; return 0 ;;
-		 "n" | "N") echo n ; return 1 ;;
+		 "y" | "Y" ) echo y ; return 0 ;;
+		 "n" | "N") break ;;
+		 "" ) if [ -t 1 ] ; then
+			echo y ; return 0
+		      fi ;;
 		esac
 	done
+
+	echo n
+	return 1
 }
 
 try_umount() {
 	yes_no "Do you want to unmount \"$MOUNTED\"" && dry "$UMOUNT" "$MOUNTED" && return 0
-	error "Cannot proceed with mounted filesystem \"$MOUNTED\""
+	error "Cannot proceed with mounted filesystem \"$MOUNTED\"."
 }
 
 validate_parsing() {
-	test -n "$BLOCKSIZE" && test -n "$BLOCKCOUNT" || error "Cannot parse $1 output"
+	test -n "$BLOCKSIZE" && test -n "$BLOCKCOUNT" || error "Cannot parse $1 output."
 }
 ####################################
 # Resize ext2/ext3/ext4 filesystem
@@ -312,6 +427,9 @@ validate_parsing() {
 # - unmounted for downsize
 ####################################
 resize_ext() {
+	local IS_MOUNTED=0
+	detect_mounted && IS_MOUNTED=1
+
 	verbose "Parsing $TUNE_EXT -l \"$VOLUME\""
 	for i in $(LC_ALL=C "$TUNE_EXT" -l "$VOLUME"); do
 		case "$i" in
@@ -324,7 +442,7 @@ resize_ext() {
 	FSFORCE=$FORCE
 
 	if [ "$NEWBLOCKCOUNT" -lt "$BLOCKCOUNT" -o "$EXTOFF" -eq 1 ]; then
-		detect_mounted && verbose "$RESIZE_EXT needs unmounted filesystem" && try_umount
+		test $IS_MOUNTED -eq 1 && verbose "$RESIZE_EXT needs unmounted filesystem" && try_umount
 		REMOUNT=$MOUNTED
 		if test -n "$MOUNTED" ; then
 			# Forced fsck -f for umounted extX filesystem.
@@ -374,7 +492,7 @@ resize_xfs() {
 	MOUNTPOINT=$MOUNTED
 	if [ -z "$MOUNTED" ]; then
 		MOUNTPOINT=$TEMPDIR
-		temp_mount || error "Cannot mount Xfs filesystem"
+		temp_mount || error "Cannot mount Xfs filesystem."
 	fi
 	verbose "Parsing $TUNE_XFS \"$MOUNTPOINT\""
 	for i in $(LC_ALL=C "$TUNE_XFS" "$MOUNTPOINT"); do
@@ -392,7 +510,7 @@ resize_xfs() {
 	elif [ $NEWBLOCKCOUNT -eq $BLOCKCOUNT ]; then
 		verbose "Xfs filesystem already has the right size"
 	else
-		error "Xfs filesystem shrinking is unsupported"
+		error "Xfs filesystem shrinking is unsupported."
 	fi
 }
 
@@ -412,8 +530,8 @@ resize() {
 	  "ext3"|"ext2"|"ext4") resize_ext $NEWSIZE ;;
 	  "reiserfs") resize_reiser $NEWSIZE ;;
 	  "xfs") resize_xfs $NEWSIZE ;;
-	  *) error "Filesystem \"$FSTYPE\" on device \"$VOLUME\" is not supported by this tool" ;;
-	esac || error "Resize $FSTYPE failed"
+	  *) error "Filesystem \"$FSTYPE\" on device \"$VOLUME\" is not supported by this tool." ;;
+	esac || error "Resize $FSTYPE failed."
 	cleanup 0
 }
 
@@ -494,12 +612,12 @@ for i in "$TUNE_EXT" "$RESIZE_EXT" "$TUNE_REISER" "$RESIZE_REISER" \
 	test -n "$i" || error "Required command definitions in the script are missing!"
 done
 
-"$LVM" version >"$NULL" 2>&1 || error "Could not run lvm binary \"$LVM\""
+"$LVM" version >"$NULL" 2>&1 || error "Could not run lvm binary \"$LVM\"."
 $("$READLINK" -e / >"$NULL" 2>&1) || READLINK_E="-f"
 TEST64BIT=$(( 1000 * 1000000000000 ))
-test "$TEST64BIT" -eq 1000000000000000 || error "Shell does not handle 64bit arithmetic"
-$(echo Y | "$GREP" Y >"$NULL") || error "Grep does not work properly"
-test $("$DATE" -u -d"Jan 01 00:00:01 1970" +%s) -eq 1 || error "Date translation does not work"
+test "$TEST64BIT" -eq 1000000000000000 || error "Shell does not handle 64bit arithmetic."
+$(echo Y | "$GREP" Y >"$NULL") || error "Grep does not work properly."
+test $("$DATE" -u -d"Jan 01 00:00:01 1970" +%s) -eq 1 || error "Date translation does not work."
 
 
 if [ "$#" -eq 0 ] ; then
